### ISSUE TITLE
ashm_multi_rainbow_plot colour issue

### ISSUE THREAD

**Issue by rdmorin** [morinlab/GAMBLR#76] opened 2022-04-08 17:25 UTC
The lymphgen colouring example shown in the vignette using ashm_multi_rainbow_plot shows every point in grey. No errors are thrown. The points should be coloured as per the legend, which is actually coloured properly, interestingly.

```
lymphgen_colours = get_gambl_colours(classification = "lymphgen")

# This package comes with some custom (curated) data such as the regions recurrently affected by hypermutation in B-NHLs
ashm_multi_rainbow_plot(regions_to_display = c("BCL2-TSS", "MYC-TSS", "SGK1-TSS", "IGL"), custom_colours = lymphgen_colours)
```

**Comment by Kdreval** [comment] 2022-04-09 05:49
This was caused by converting a factor column into a factor.  It is addressed in #73 ✅

**Closed** 2022-04-09 16:14 UTC
