### ISSUE TITLE
Is genes an optional or required argument for prettyForestPlot + other prettyForestPlot issues

### ISSUE THREAD

**Issue by rdmorin** [morinlab/GAMBLR#145] opened 2022-12-09 17:29 UTC
The documentation says that `genes` is optional but when I run this function without it I get an error. Can the function be fixed to work without this option specified and/or the docs be updated to make this required?

```
prettyForestPlot(maf=bl_coding,metadata=bl_meth_meta,comparison_column="cluster",comparison_values=c("cluster1","cluster2"))
 Error in h(simpleError(msg, call)) : 
error in evaluating the argument 'table' in selecting a method for function '%in%': argument "genes" is missing, with no default
```

**Comment by mattssca** [comment] 2022-12-09 18:15
I think it's best to update the documentation for this function so that it is clear that `genes` is a required parameter. 

Specified genes in this parameter are required to filter the incoming maf and this is what the error you are seeing relates to. 

In addition, there is a check at the beginning of this function that is meant to stop the function if no genes are provided. However, this currently does not work as intended. Will be fixed in a PR dedicated to resolving the issues raised for this function.

**Comment by mattssca** [comment] 2022-12-09 18:16
There's another issue related to this plot:
```
prettyForestPlot(maf=bl_coding,metadata=bl_meth_meta,comparison_column="cluster",comparison_values=c("cluster1","cluster2"),genes=dlbcl_genes,max_q = 0.1)
FONT: 20 POINT: Inf 0
Error in `check_aesthetics()`:
! Aesthetics must be either length 1 or the same as the data (1): ymin, ymax, x and y
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by rdmorin** [comment] 2022-12-09 19:50
Wouldn't it be better to have it work as advertised though? Some folks may want to run the test on all genes rather than have to subset them upfront

**Comment by mattssca** [comment] 2022-12-09 19:53
Of course, that sounds reasonable. I can add this functionality, no problem.

**Comment by rdmorin** [comment] 2023-01-19 17:39
Resolved?

**Comment by mattssca** [comment] 2023-01-19 17:40
Resolved!

**Closed by mattssca** 2023-01-19 17:40 UTC
